import bcrypt from "bcryptjs";

const demoPasswordHash = bcrypt.hashSync("Demo@123", 10);

const mockStudents = [
    {
        _id: "student_1",
        fullname: "Amit Sharma",
        email: "amit.student@demo.com",
        phoneNumber: 9000000001,
        password: demoPasswordHash,
        role: "student",
        profile: {
            bio: "Frontend Engineer experienced in React, TypeScript, and accessible UI systems.",
            skills: ["JavaScript", "React", "TypeScript", "HTML", "CSS", "Tailwind"],
            profilePhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
    },
    {
        _id: "student_2",
        fullname: "Rahul Das",
        email: "rahul.student@demo.com",
        phoneNumber: 9000000002,
        password: demoPasswordHash,
        role: "student",
        profile: {
            bio: "Financial Analyst and Operations Specialist with expertise in portfolio modeling, valuation, and forecasting.",
            skills: ["Financial Modeling", "Excel", "Valuation", "Risk Analysis", "Accounting", "Data Analysis"],
            profilePhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
    },
    {
        _id: "student_3",
        fullname: "Pooja Verma",
        email: "pooja.student@demo.com",
        phoneNumber: 9000000003,
        password: demoPasswordHash,
        role: "student",
        profile: {
            bio: "Healthcare Clinical Specialist and Patient Care Coordinator with 3+ years experience in hospital operations.",
            skills: ["Patient Care", "Clinical Operations", "EHR", "Healthcare Quality", "Medical Documentation"],
            profilePhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
    }
];

const mockRecruiters = [
    {
        _id: "recruiter_1",
        fullname: "Rohan Mehta",
        email: "rohan.recruiter@demo.com",
        phoneNumber: 9100000001,
        password: demoPasswordHash,
        role: "recruiter",
        isSubUser: false,
        profile: {
            bio: "Director of Global Talent Acquisition across Technology, Healthcare, Finance, and Marketing.",
            skills: ["Cross-Industry Hiring", "Executive Recruitment", "Talent Strategy"],
            profilePhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
        subUsers: [
            {
                _id: "subuser_maya_1",
                name: "Maya Chen",
                email: "maya.chen@demo.com",
                password: "Demo@123",
                role: "Technical Interviewer",
                department: "Engineering Core",
                specialty: ["React", "TypeScript", "System Architecture"],
                phone: "9100000088",
                permissions: {
                    canViewAssignedInterviews: true,
                    canConductInterview: true,
                    canSubmitReport: true,
                    canViewAllInterviews: false,
                    canPostJobs: false,
                    canViewAllApplicants: false,
                    canManageCompanies: false,
                    canFinalizeHiringDecision: false,
                },
                userId: "subuser_maya_user_1",
                createdAt: new Date("2026-02-01").toISOString(),
            }
        ]
    },
    {
        _id: "subuser_maya_user_1",
        fullname: "Maya Chen",
        email: "maya.chen@demo.com",
        phoneNumber: 9100000088,
        password: demoPasswordHash,
        role: "recruiter",
        isSubUser: true,
        parentRecruiter: "recruiter_1",
        subRole: "Technical Interviewer",
        department: "Engineering Core",
        specialty: ["React", "TypeScript", "System Architecture"],
        permissions: {
            canViewAssignedInterviews: true,
            canConductInterview: true,
            canSubmitReport: true,
            canViewAllInterviews: false,
            canPostJobs: false,
            canViewAllApplicants: false,
            canManageCompanies: false,
            canFinalizeHiringDecision: false,
        },
        profile: {
            bio: "Technical Interviewer - Engineering Core",
            skills: ["React", "TypeScript", "System Architecture"],
            profilePhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
        subUsers: [],
    }
];

const mockAdmins = [
    {
        _id: "admin_super_1",
        fullname: "HireHub System Administrator",
        email: "admin@hirehub.internal",
        phoneNumber: 9999999999,
        password: demoPasswordHash,
        role: "admin",
        profile: {
            bio: "Website Administrator with unrestricted global privileges, database diagnostics, and management facilities.",
            skills: ["Database Management", "System Architecture", "Security Auditing"],
            profilePhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
        subUsers: []
    }
];

const mockCompanies = [
    {
        _id: "company_1",
        name: "TechNova Solutions",
        description: "Technology enterprise building cloud infrastructure, distributed microservices, and AI software.",
        website: "https://technova.example.com",
        location: "Bengaluru",
        logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-10").toISOString(),
    },
    {
        _id: "company_2",
        name: "Apex Healthcare & Clinical Systems",
        description: "Premier healthcare network offering advanced multi-specialty clinical care, research, and patient health systems.",
        website: "https://apexhealth.example.com",
        location: "Mumbai",
        logo: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-12").toISOString(),
    },
    {
        _id: "company_3",
        name: "Meridian Financial Capital",
        description: "Global investment banking, asset management, and risk consultancy firm managing institutional portfolios.",
        website: "https://meridiancap.example.com",
        location: "Delhi NCR",
        logo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-15").toISOString(),
    },
    {
        _id: "company_4",
        name: "OmniGrowth Media & Marketing",
        description: "Performance marketing agency accelerating customer acquisition, omnichannel growth, and brand campaigns.",
        website: "https://omnigrowth.example.com",
        location: "Bengaluru",
        logo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-18").toISOString(),
    },
    {
        _id: "company_5",
        name: "GlobalLink Logistics & Operations",
        description: "International supply chain network managing multimodal logistics, automated fulfillment, and fleet operations.",
        website: "https://globallink.example.com",
        location: "Hyderabad",
        logo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-20").toISOString(),
    }
];

const mockJobs = [
    {
        _id: "job_1",
        title: "Frontend Developer (React & TypeScript)",
        description: "We are looking for a skilled Frontend Engineer to build intuitive, high-performance web applications using React, TypeScript, and modern component systems.",
        requirements: ["React", "TypeScript", "JavaScript", "HTML", "CSS", "Tailwind CSS"],
        salary: 14,
        experienceLevel: 2,
        location: "Bengaluru",
        jobType: "Full-time",
        position: 3,
        company: mockCompanies[0],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-01").toISOString(),
    },
    {
        _id: "job_2",
        title: "Clinical Nurse Specialist / Operations Lead",
        description: "Lead patient care workflows, supervise ICU/acute care procedures, and collaborate with cross-functional healthcare teams to ensure clinical compliance and superior care quality.",
        requirements: ["Patient Care", "Clinical Operations", "EHR", "Healthcare Quality", "Emergency Care"],
        salary: 11,
        experienceLevel: 3,
        location: "Mumbai",
        jobType: "Full-time",
        position: 4,
        company: mockCompanies[1],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-04").toISOString(),
    },
    {
        _id: "job_3",
        title: "Senior Financial Analyst & Valuation Lead",
        description: "Conduct financial modeling, risk assessment, corporate valuation, and strategic forecasting for high-growth enterprise portfolios and investment rounds.",
        requirements: ["Financial Modeling", "Excel", "Valuation", "Risk Analysis", "Corporate Finance", "GAAP"],
        salary: 18,
        experienceLevel: 4,
        location: "Delhi NCR",
        jobType: "Full-time",
        position: 2,
        company: mockCompanies[2],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-07").toISOString(),
    },
    {
        _id: "job_4",
        title: "Growth Marketing Manager & Campaign Strategist",
        description: "Spearhead performance marketing, customer acquisition funnels, digital ad campaigns, SEO, and omnichannel brand messaging to drive scalable revenue expansion.",
        requirements: ["Marketing Strategy", "Performance Ads", "SEO", "Content Marketing", "Data Analytics", "Conversion Optimization"],
        salary: 13,
        experienceLevel: 3,
        location: "Bengaluru",
        jobType: "Full-time",
        position: 2,
        company: mockCompanies[3],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-10").toISOString(),
    },
    {
        _id: "job_5",
        title: "Supply Chain & Operations Manager",
        description: "Oversee end-to-end warehouse logistics, freight procurement, inventory optimization, and vendor SLA management across regional fulfillment hubs.",
        requirements: ["Supply Chain", "Logistics", "Operations Management", "Inventory Control", "Vendor Negotiation"],
        salary: 15,
        experienceLevel: 3,
        location: "Hyderabad",
        jobType: "Full-time",
        position: 3,
        company: mockCompanies[4],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-12").toISOString(),
    }
];

const mockApplications = [];

const mockInterviews = [
    {
        _id: "interview_1",
        job: mockJobs[0],
        candidate: mockStudents[0],
        recruiter: mockRecruiters[0],
        company: mockCompanies[0],
        interviewDate: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        interviewTime: "14:00",
        durationMinutes: 45,
        roundType: "Technical Round",
        status: "scheduled",
        roomId: "hh-tech-live01",
        meetingLink: "/interview/room/hh-tech-live01",
        notes: "Deep dive into React state patterns, component optimization, and custom hooks.",
        interviewerType: "recruiter",
        assignedInterviewer: {
            name: "Rohan Mehta",
            email: "rohan.recruiter@demo.com",
            role: "Lead Recruiter",
            department: "Talent & Engineering",
            notes: "Direct evaluation of React state patterns, component optimization, and custom hooks.",
        },
        panelistReport: {
            isSubmitted: false,
            technicalScore: 0,
            problemSolvingScore: 0,
            systemDesignScore: 0,
            communicationScore: 0,
            overallRating: 0,
            panelistRecommendation: "Undecided",
        },
        recruiterFinalDecision: {
            isFinalized: false,
            finalDecision: "Pending Review",
        },
        sharedCode: "// Live React / JavaScript Workspace\nfunction solveProblem(arr) {\n    // Implement solution\n    return arr;\n}\n",
        sharedLanguage: "javascript",
        chatMessages: [],
        createdAt: new Date().toISOString(),
    },
    {
        _id: "interview_2",
        job: mockJobs[1],
        candidate: mockStudents[1],
        recruiter: mockRecruiters[0],
        company: mockCompanies[1],
        interviewDate: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        interviewTime: "16:30",
        durationMinutes: 60,
        roundType: "System Architecture & Leadership",
        status: "scheduled",
        roomId: "hh-rec-lead02",
        meetingLink: "/interview/room/hh-rec-lead02",
        notes: "Direct evaluation by Master Recruiter for architectural vision and cultural alignment.",
        interviewerType: "recruiter",
        assignedInterviewer: {
            name: "Rohan Mehta",
            email: "rohan.recruiter@demo.com",
            role: "Lead Technical Recruiter",
            department: "Talent & Engineering Leadership",
        },
        panelistReport: {
            isSubmitted: false,
        },
        recruiterFinalDecision: {
            isFinalized: false,
            finalDecision: "Pending Review",
        },
        sharedCode: "// High Scale Architecture Discussion\n// System components, caching strategy, database partitioning\n",
        sharedLanguage: "javascript",
        chatMessages: [],
        createdAt: new Date().toISOString(),
    },
    {
        _id: "interview_3",
        job: mockJobs[0],
        candidate: mockStudents[1],
        recruiter: mockRecruiters[0],
        company: mockCompanies[0],
        interviewDate: new Date(Date.now() + 43200000).toISOString().split("T")[0],
        interviewTime: "11:00",
        durationMinutes: 45,
        roundType: "Frontend Engineering Round",
        status: "scheduled",
        roomId: "hh-maya-live03",
        meetingLink: "/interview/room/hh-maya-live03",
        notes: "Assigned to Panel Interviewer Maya Chen for React state, styling, and DOM performance assessment.",
        interviewerType: "panelist",
        assignedInterviewer: {
            name: "Maya Chen",
            email: "maya.chen@demo.com",
            role: "Technical Interviewer",
            department: "Engineering Core",
            subUserId: "subuser_maya_1",
            notes: "Focus on React component optimization and system design fundamentals.",
        },
        panelistReport: {
            isSubmitted: false,
            technicalScore: 0,
            problemSolvingScore: 0,
            systemDesignScore: 0,
            communicationScore: 0,
            overallRating: 0,
            panelistRecommendation: "Undecided",
        },
        recruiterFinalDecision: {
            isFinalized: false,
            finalDecision: "Pending Review",
        },
        sharedCode: "// Maya Chen's Evaluation Pad\n// Candidate: Priya Sharma\nfunction optimizeList(items) {\n    // Code here\n}\n",
        sharedLanguage: "javascript",
        chatMessages: [],
        createdAt: new Date().toISOString(),
    }
];

export const mockStore = {
    users: [...mockStudents, ...mockRecruiters, ...mockAdmins],
    companies: [...mockCompanies],
    jobs: [...mockJobs],
    applications: [...mockApplications],
    interviews: [...mockInterviews],
};
