import bcrypt from "bcryptjs";

const demoPasswordHash = bcrypt.hashSync("Demo@123", 10);

const mockStudents = [
    {
        _id: "student_1",
        fullname: "Amit Sharma",
        email: "amit.student@demo.com",
        phoneNumber: 9000000001,
        password: demoPasswordHash,
        role: "student",
        profile: {
            bio: "Frontend Developer experienced in React and Tailwind CSS.",
            skills: ["JavaScript", "React", "HTML", "CSS", "Tailwind"],
            profilePhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
    },
    {
        _id: "student_2",
        fullname: "Rahul Das",
        email: "rahul.student@demo.com",
        phoneNumber: 9000000002,
        password: demoPasswordHash,
        role: "student",
        profile: {
            bio: "Full Stack Engineer specializing in Node.js, Express, and React.",
            skills: ["Node.js", "Express.js", "MongoDB", "React", "REST API"],
            profilePhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
    }
];

const mockRecruiters = [
    {
        _id: "recruiter_1",
        fullname: "Rohan Mehta",
        email: "rohan.recruiter@demo.com",
        phoneNumber: 9100000001,
        password: demoPasswordHash,
        role: "recruiter",
        isSubUser: false,
        profile: {
            bio: "Lead Technical Recruiter at TechNova Solutions.",
            skills: ["Tech Hiring", "Talent Acquisition"],
            profilePhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
            resume: "",
            resumeOriginalName: "",
        },
        subUsers: [
            {
                _id: "subuser_1",
                name: "Alex Rivera",
                email: "alex.rivera@eng.company.com",
                password: "Demo@123",
                role: "Staff Backend Engineer",
                department: "Distributed Systems & Cloud",
                specialty: ["Node.js", "Go", "Kubernetes", "System Design"],
                phone: "+1-555-0192",
                permissions: {
                    canViewAssignedInterviews: true,
                    canConductInterview: true,
                    canSubmitReport: true,
                    canViewAllInterviews: false,
                    canPostJobs: false,
                    canViewAllApplicants: false,
                    canManageCompanies: false,
                    canFinalizeHiringDecision: false,
                },
                createdAt: new Date("2026-02-10").toISOString(),
            },
            {
                _id: "subuser_2",
                name: "Priya Nair",
                email: "priya.nair@eng.company.com",
                password: "Demo@123",
                role: "Senior Frontend Architect",
                department: "Web Platform & UI Core",
                specialty: ["React", "TypeScript", "Performance", "CSS/Web Standards"],
                phone: "+1-555-0144",
                permissions: {
                    canViewAssignedInterviews: true,
                    canConductInterview: true,
                    canSubmitReport: true,
                    canViewAllInterviews: false,
                    canPostJobs: false,
                    canViewAllApplicants: false,
                    canManageCompanies: false,
                    canFinalizeHiringDecision: false,
                },
                createdAt: new Date("2026-02-12").toISOString(),
            }
        ]
    },
    {
        _id: "subuser_1_user",
        fullname: "Alex Rivera",
        email: "alex.rivera@eng.company.com",
        phoneNumber: 9100000092,
        password: demoPasswordHash,
        role: "recruiter",
        isSubUser: true,
        parentRecruiter: "recruiter_1",
        subRole: "Staff Backend Engineer",
        department: "Distributed Systems & Cloud",
        specialty: ["Node.js", "Go", "Kubernetes", "System Design"],
        permissions: {
            canViewAssignedInterviews: true,
            canConductInterview: true,
            canSubmitReport: true,
            canViewAllInterviews: false,
            canPostJobs: false,
            canViewAllApplicants: false,
            canManageCompanies: false,
            canFinalizeHiringDecision: false,
        },
        profile: {
            bio: "Staff Backend Engineer conducting specialized distributed systems & Node.js technical rounds.",
            skills: ["Node.js", "Go", "Kubernetes", "System Design"],
            profilePhoto: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
        }
    },
    {
        _id: "subuser_2_user",
        fullname: "Priya Nair",
        email: "priya.nair@eng.company.com",
        phoneNumber: 9100000044,
        password: demoPasswordHash,
        role: "recruiter",
        isSubUser: true,
        parentRecruiter: "recruiter_1",
        subRole: "Senior Frontend Architect",
        department: "Web Platform & UI Core",
        specialty: ["React", "TypeScript", "Performance", "CSS/Web Standards"],
        permissions: {
            canViewAssignedInterviews: true,
            canConductInterview: true,
            canSubmitReport: true,
            canViewAllInterviews: false,
            canPostJobs: false,
            canViewAllApplicants: false,
            canManageCompanies: false,
            canFinalizeHiringDecision: false,
        },
        profile: {
            bio: "Senior Frontend Architect conducting deep React & Web architecture evaluations.",
            skills: ["React", "TypeScript", "Performance", "CSS"],
            profilePhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
        }
    }
];

const mockCompanies = [
    {
        _id: "company_1",
        name: "TechNova Solutions",
        description: "Technology company developing modern software solutions and cloud infrastructure.",
        website: "https://technova.example.com",
        location: "Bengaluru",
        logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-10").toISOString(),
    },
    {
        _id: "company_2",
        name: "DataSphere Analytics",
        description: "Leading enterprise data analytics and AI intelligence platform provider.",
        website: "https://datasphere.example.com",
        location: "Hyderabad",
        logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-15").toISOString(),
    },
    {
        _id: "company_3",
        name: "CloudBridge Technologies",
        description: "Next-generation cloud architectures and microservice deployment solutions.",
        website: "https://cloudbridge.example.com",
        location: "Pune",
        logo: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&auto=format&fit=crop&q=80",
        userId: "recruiter_1",
        createdAt: new Date("2026-01-20").toISOString(),
    }
];

const mockJobs = [
    {
        _id: "job_1",
        title: "Frontend Developer (React)",
        description: "We are looking for a passionate Frontend Developer with strong expertise in React, Redux, and modern CSS frameworks.",
        requirements: ["React", "JavaScript", "HTML", "CSS", "Tailwind"],
        salary: 12,
        experienceLevel: 2,
        location: "Bengaluru",
        jobType: "Full-time",
        position: 4,
        company: mockCompanies[0],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-01").toISOString(),
    },
    {
        _id: "job_2",
        title: "Full Stack Engineer (MERN)",
        description: "Join our core product engineering team building high-scale real-time web applications using React and Node.js.",
        requirements: ["React", "Node.js", "Express.js", "MongoDB", "REST API"],
        salary: 18,
        experienceLevel: 3,
        location: "Hyderabad",
        jobType: "Full-time",
        position: 2,
        company: mockCompanies[1],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-05").toISOString(),
    },
    {
        _id: "job_3",
        title: "Backend Developer (Node.js)",
        description: "Design and implement scalable backend microservices, robust API integrations, and secure database architectures.",
        requirements: ["Node.js", "Express.js", "MongoDB", "SQL", "Docker"],
        salary: 15,
        experienceLevel: 2,
        location: "Pune",
        jobType: "Full-time",
        position: 3,
        company: mockCompanies[2],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-10").toISOString(),
    },
    {
        _id: "job_4",
        title: "Junior Software Engineer",
        description: "Great opportunity for fresh graduates and early career developers to learn and grow in a fast-paced technology environment.",
        requirements: ["JavaScript", "Python", "Problem Solving", "Git"],
        salary: 8,
        experienceLevel: 0,
        location: "Remote",
        jobType: "Full-time",
        position: 5,
        company: mockCompanies[0],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-12").toISOString(),
    },
    {
        _id: "job_5",
        title: "UI/UX Designer & Developer",
        description: "Transform user workflows into intuitive, beautiful design systems, responsive wireframes, and production-ready components.",
        requirements: ["Figma", "UI Design", "UX Design", "HTML", "CSS", "React"],
        salary: 14,
        experienceLevel: 2,
        location: "Bengaluru",
        jobType: "Full-time",
        position: 2,
        company: mockCompanies[1],
        created_by: "recruiter_1",
        applications: [],
        createdAt: new Date("2026-02-14").toISOString(),
    }
];

const mockApplications = [];

const mockInterviews = [
    {
        _id: "interview_1",
        job: mockJobs[0],
        candidate: mockStudents[0],
        recruiter: mockRecruiters[0],
        company: mockCompanies[0],
        interviewDate: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        interviewTime: "14:00",
        durationMinutes: 45,
        roundType: "Technical Round",
        status: "scheduled",
        roomId: "hh-tech-live01",
        meetingLink: "/interview/room/hh-tech-live01",
        notes: "Deep dive into React state patterns, component optimization, and custom hooks.",
        interviewerType: "assigned_panelist",
        assignedInterviewer: {
            name: "Alex Rivera",
            email: "alex.rivera@eng.company.com",
            role: "Staff Backend Engineer",
            department: "Distributed Systems & Cloud",
            notes: "Please evaluate data structures, async Node APIs, and problem solving efficiency.",
            subUserId: "subuser_1",
            userId: "subuser_1_user",
        },
        panelistReport: {
            isSubmitted: false,
            technicalScore: 0,
            problemSolvingScore: 0,
            systemDesignScore: 0,
            communicationScore: 0,
            overallRating: 0,
            panelistRecommendation: "Undecided",
        },
        recruiterFinalDecision: {
            isFinalized: false,
            finalDecision: "Pending Review",
        },
        sharedCode: "// Live React / JavaScript Workspace\nfunction solveProblem(arr) {\n    // Implement solution\n    return arr;\n}\n",
        sharedLanguage: "javascript",
        chatMessages: [],
        createdAt: new Date().toISOString(),
    },
    {
        _id: "interview_2",
        job: mockJobs[1],
        candidate: mockStudents[1],
        recruiter: mockRecruiters[0],
        company: mockCompanies[1],
        interviewDate: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        interviewTime: "16:30",
        durationMinutes: 60,
        roundType: "System Architecture & Leadership",
        status: "scheduled",
        roomId: "hh-rec-lead02",
        meetingLink: "/interview/room/hh-rec-lead02",
        notes: "Direct evaluation by Master Recruiter for architectural vision and cultural alignment.",
        interviewerType: "recruiter",
        assignedInterviewer: {
            name: "Rohan Mehta",
            email: "rohan.recruiter@demo.com",
            role: "Lead Technical Recruiter",
            department: "Talent & Engineering Leadership",
        },
        panelistReport: {
            isSubmitted: false,
        },
        recruiterFinalDecision: {
            isFinalized: false,
            finalDecision: "Pending Review",
        },
        sharedCode: "// High Scale Architecture Discussion\n// System components, caching strategy, database partitioning\n",
        sharedLanguage: "javascript",
        chatMessages: [],
        createdAt: new Date().toISOString(),
    }
];

export const mockStore = {
    users: [...mockStudents, ...mockRecruiters],
    companies: [...mockCompanies],
    jobs: [...mockJobs],
    applications: [...mockApplications],
    interviews: [...mockInterviews],
};
